### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by T8RIN** [zed-alpha/shadow-gadgets#1]
I use many shadows and this causes ANRS really often

![image](https://github.com/zed-alpha/shadow-gadgets/assets/52178347/6ad5800a-5731-4f44-a470-1472cd6696c2)

**Comment by zed-alpha** [comment]
Hi there! Thank you for the report. If you could, please provide some more information, and I'll try to take a look at this as soon as I can.

1. Which library version are you using?
1. Did this start when you updated the library version? Or has this always been an issue?
1. Which versions of Android are affected?
1. Are you using the View version, or Compose?
1. If you're using Views, are you changing the `[Clipped]ShadowPlane` from the default `Foreground`? If so, which ones are you using?
1. How many library shadows are you using at once?

An example or outline of your setup would be really helpful, too, or if your project is publicly available, I'm happy to take a look at it directly.

Sorry for the trouble. Hope I can get something figured out to fix it.

**Comment by T8RIN** [comment]
1) latest
2) always
3) all versions i think 
4) compose
6) There could be at least 20 on the screen at a time, I’m not even sure if this is really a problem with your library, or in principle drawing so many shadows, although I changed it to regular ones, it seems to have gotten better

[ImageToolbox](https://GitHub.com/t8rin/ImageToolbox)

**Comment by zed-alpha** [comment]
Ah, OK, yeah, that's likely my fault somewhere. I haven't tested the Compose version nearly as much as I have Views.

Thanks for the project link; extremely helpful. This issue will be the top priority for the next release, but I can't guarantee anything at the moment.

**Comment by T8RIN** [comment]
No problems :)

**Comment by zed-alpha** [comment]
Hi, @T8RIN.

I've been playing around with your app for a couple of days now, but I haven't ever been able to cause an ANR. I only have access to the emulators and my personal devices at the moment, but I've tested every Android version from Lollipop to Tiramisu without a single ANR happening.

The only crashes I had were `OutOfMemoryError`s whenever I tried to stitch too many images, and `IndexOutOfBoundsException`s that look to be the same problem that someone's already noted in [this issue on your repo](https://github.com/T8RIN/ImageToolbox/issues/507). The `IndexOutOfBoundsException` is likely a new bug in Compose, since it seems that others are getting it too: https://stackoverflow.com/q/77357872. I triggered it on the "Single edit" screen by loading an image, then toggling the lock/unlock button beside the image size slider a couple of times.

The only behavior I saw that I think might potentially relate to an ANR is an infinite redraw loop – on Tiramisu only – that seems to repeatedly invalidate itself, so everything is redrawn constantly. It happens without using any shadows, and even without the `Marquee` or any other animations running, so there's something else causing it, but I haven't yet had a chance to pinpoint exactly what. I don't know if the Compose tooling shows redraw count anywhere, but you can see it in action by using the [Profile GPU/HWUI rendering](https://developer.android.com/topic/performance/rendering/inspect-gpu-rendering#enable_rendering_profiler) developer tool on the device itself.

Since that only occurs on Tiramisu, though, I'm not sure if it's even related to the ANRs. Do you get any more information with those reports? Like Android version percentages, or maybe device brands, or memory specifications, etc.? After all the emulators passed my tests, I started to think that maybe it's only an issue on lower-end devices?

Also, do you know any specific way to cause an ANR in your app directly? Or do they just happen randomly?

**Comment by T8RIN** [comment]
Which version did you watch? Thank you for such a detailed analysis 🐸 I tried to fix this recently and noticed that the load was being drawn too big for some reason, causing the shadow to hang, I think I fixed this in 2.4.2

It even seems to me that this is not a problem with your library, but something deeper, at the C++ level

**Comment by zed-alpha** [comment]
Oh, yeah, I didn't even think to check the current version against the ANR report. It looks like I've been running 2.4.2-alpha02, so it does seem like you might have it fixed already.

I'll leave this issue open for now, in case we missed something, or if you have any other questions or concerns with the ANRs. I'm having trouble getting notifications at the moment, but I'll try to remember to check back here regularly.

Cheers!

**Comment by T8RIN** [comment]
> Oh, yeah, I didn't even think to check the current version against the ANR report. It looks like I've been running 2.4.2-alpha02, so it does seem like you might have it fixed already.
> 
> I'll leave this issue open for now, in case we missed something, or if you have any other questions or concerns with the ANRs. I'm having trouble getting notifications at the moment, but I'll try to remember to check back here regularly.
> 
> Cheers!

Okay, thanks a lot :) ❤️
